# Generated by Django 5.2.3 on 2025-08-15 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen')], max_length=10)),
                ('texto', models.TextField()),
                ('image', models.ImageField(upload_to='portafolio/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.portafolio')),
            ],
            options={
                'verbose_name': 'Detalle de Proyecto',
                'verbose_name_plural': 'Detalles de Proyectos',
                'ordering': ['order'],
            },
        ),
    ]
