# Generated by Django 5.2.3 on 2025-09-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0002_alter_portafolio_image_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('git_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='tag',
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='portafolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.project'),
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.tag')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(related_name='Tag', through='portafolios.ProjectTag', to='portafolios.tag'),
        ),
        migrations.DeleteModel(
            name='PortafolioTag',
        ),
        migrations.DeleteModel(
            name='Portafolio',
        ),
    ]
