# Generated by Django 5.2.3 on 2025-07-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='tag',
            field=models.ManyToManyField(related_name='Tag', through='faq.Faq_tag', to='faq.tag'),
        ),
    ]
