# Generated by Django 5.2.3 on 2025-09-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='detail',
        ),
        migrations.CreateModel(
            name='Faq_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('code', models.TextField(blank=True, null=True)),
                ('code_type', models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('shell', 'Shell'), ('bash', 'Bash'), ('other', 'Other'), ('', 'Blank')], default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.faq')),
            ],
            options={
                'verbose_name': 'Detalle de Pregunta',
                'verbose_name_plural': 'Detalles de Preguntas',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
